name: tests-code-coverage

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: make install
      - name: Run linter
        run: make lint
      - name: Codeclimate test coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
           CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ID }}
        with:
            coverageCommand: make test-coverage
